// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// CAN ID
#ifndef CONF_CONTROLLER_ID
#define CONF_CONTROLLER_ID 104
#endif

// CAN Status Rate
#ifndef CONF_SEND_CAN_STATUS_RATE_HZ
#define CONF_SEND_CAN_STATUS_RATE_HZ 10
#endif

// CAN Baud Rate
#ifndef CONF_CAN_BAUD_RATE
#define CONF_CAN_BAUD_RATE 2
#endif

// CONF_DEFAULT_H_
#endif

